# Generated by Django 2.2.5 on 2020-01-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200114_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='territory',
            options={'ordering': ['code'], 'verbose_name': 'Territory', 'verbose_name_plural': 'Territories'},
        ),
    ]
