# Generated by Django 2.2.5 on 2020-01-12 17:25

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191218_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='code',
        ),
        migrations.RemoveField(
            model_name='region',
            name='code',
        ),
        migrations.AlterField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Region', verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(choices=[('chu', 'Chue'), ('osh', 'Osh'), ('bat', 'Batken'), ('jal', 'Jalalabad'), ('tal', 'Talas'), ('nar', 'Narin'), ('kol', 'Issikkol')], max_length=9, unique=True, verbose_name='name'),
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='name')),
                ('counter', models.CharField(default=users.models.increment_territory_country, editable=False, max_length=4, verbose_name='counter of Territory')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.District')),
            ],
            options={
                'verbose_name': 'Territory',
                'verbose_name_plural': 'Territories',
            },
        ),
    ]
