# Generated by Django 2.2.5 on 2020-01-10 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191218_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='region',
            field=models.ForeignKey(max_length=9, on_delete=django.db.models.deletion.CASCADE, to='users.Region', verbose_name='region'),
        ),
    ]
