# Generated by Django 2.2.5 on 2020-01-20 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200119_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.District', verbose_name='district'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('district', 'agreement')},
        ),
    ]
