# Generated by Django 2.2.5 on 2020-01-12 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200112_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='territory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Territory', verbose_name='residence'),
            preserve_default=False,
        ),
    ]
