# Generated by Django 2.2.5 on 2020-01-28 03:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200120_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'Район', 'verbose_name_plural': 'Райондор'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Кызматкер', 'verbose_name_plural': 'Кызматкерлер'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Облус', 'verbose_name_plural': 'Облустар'},
        ),
        migrations.AlterModelOptions(
            name='territory',
            options={'ordering': ['code'], 'verbose_name': 'Территория', 'verbose_name_plural': 'Территориялар'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Колдонуучу', 'verbose_name_plural': 'Колдонуучулар'},
        ),
        migrations.AddField(
            model_name='employee',
            name='is_badge_printed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_badge_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='district',
            name='counter',
            field=models.CharField(default='000001', max_length=8),
        ),
        migrations.AlterField(
            model_name='district',
            name='gov_admin',
            field=models.CharField(max_length=255, verbose_name='Мам админстрациа башчы (ААТ)'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=55, verbose_name='аты'),
        ),
        migrations.AlterField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Region', verbose_name='облус'),
        ),
        migrations.AlterField(
            model_name='district',
            name='stat_admin',
            field=models.CharField(max_length=255, verbose_name='Статистика башчы (ААТ)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='PIN',
            field=models.CharField(max_length=14, verbose_name='ПИН'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=255, verbose_name='дарек'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='agreement',
            field=models.CharField(max_length=6, verbose_name='келишим'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='authority',
            field=models.CharField(max_length=10, verbose_name='паспорт берген орган'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_day',
            field=models.DateField(verbose_name='туулган күнү'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ишке алынган күнү'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15')], default=1, verbose_name='каттоо бөлүмү'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.District', verbose_name='район'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=45, verbose_name='аты'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('2', 'эркек'), ('1', 'аял')], default='2', max_length=1, verbose_name='жынысы'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=45, verbose_name='фамилиясы'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='login',
            field=models.CharField(max_length=50, verbose_name='логин'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='number',
            field=models.CharField(error_messages={'unique': 'Мундай номер бар.'}, max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='must be in 123456789 format!', regex='^\\d{9}$')], verbose_name='телефон номуру'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport_num',
            field=models.CharField(max_length=7, verbose_name='паспорт номуру'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=16, verbose_name='пароль'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='patronymic',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='атасынын аты'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(upload_to='users/img', verbose_name='сүрөт'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='plot',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15')], default=1, verbose_name='каттоо участогу'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='users/qr-codes', verbose_name='QR код'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('enum', 'Каттоочу'), ('ins', 'Инструктор'), ('cor', 'Координатор')], default=('cor', 'Координатор'), max_length=50, verbose_name='ролу'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sector',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15')], default=1, verbose_name='инструктордук участок'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='serial',
            field=models.CharField(choices=[('ID', 'ID'), ('AN', 'AN'), ('AC', 'AC')], default='ID', max_length=2, verbose_name='паспорт сериясы'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Territory', verbose_name='территория'),
        ),
        migrations.AlterField(
            model_name='region',
            name='address',
            field=models.CharField(max_length=255, verbose_name='дарек'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(choices=[('chu', 'Чүй'), ('osh', 'Ош'), ('bat', 'Баткен'), ('jal', 'Жалал-Абад'), ('tal', 'Талас'), ('nar', 'Нарын'), ('kol', 'Ысык-Көл')], max_length=9, unique=True, verbose_name='аты'),
        ),
        migrations.AlterField(
            model_name='territory',
            name='code',
            field=models.CharField(max_length=14, unique=True, verbose_name='Коду'),
        ),
        migrations.AlterField(
            model_name='territory',
            name='counter',
            field=models.CharField(default=users.models.increment_territory_country, editable=False, max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='territory',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.District', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='territory',
            name='name',
            field=models.CharField(max_length=90, verbose_name='Аты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.District', verbose_name='район'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='кызматкер статусу'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='башкаруучу'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='must be in 123456789 format!', regex='^\\d{9}$')], verbose_name='номуру'),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Region', verbose_name='облус'),
        ),
    ]
