# Generated by Django 2.2.5 on 2020-01-12 17:58

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_employee_territory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territory',
            name='counter',
            field=models.CharField(default=users.models.increment_territory_country, max_length=4, verbose_name='counter of Territory'),
        ),
    ]
