# Generated by Django 2.2.5 on 2020-02-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200129_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='login',
            field=models.CharField(max_length=14, verbose_name='логин'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=18, verbose_name='пароль'),
        ),
    ]
