# Generated by Django 2.2.5 on 2020-01-12 18:05

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200112_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territory',
            name='counter',
            field=models.CharField(default=users.models.increment_territory_country, editable=False, max_length=4, unique=True, verbose_name='counter of Territory'),
        ),
    ]
