# Generated by Django 2.2.8 on 2020-02-18 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200204_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-id'], 'verbose_name': 'Кызматкер', 'verbose_name_plural': 'Кызматкерлер'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('print_badge', 'Can print a badge'), ('close_task', 'Can print an agreement')], 'verbose_name': 'Колдонуучу', 'verbose_name_plural': 'Колдонуучулар'},
        ),
    ]
