# Generated by Django 2.2.8 on 2020-02-18 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200218_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_print_badge', 'Can print a badge'), ('can_print_agreement', 'Can print an agreement')], 'verbose_name': 'Колдонуучу', 'verbose_name_plural': 'Колдонуучулар'},
        ),
    ]
