# Generated by Django 2.2.8 on 2020-02-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200218_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='login',
            field=models.CharField(max_length=9, verbose_name='логин'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=13, verbose_name='пароль'),
        ),
    ]
