# Generated by Django 2.2.8 on 2020-02-19 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200219_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='must be in 123456789 format!', regex='^\\d{9}$')], verbose_name='number'),
        ),
    ]
