# Generated by Django 2.2.8 on 2020-02-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200220_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('census_start_date', models.DateField()),
                ('census_end_date', models.DateField()),
                ('coordinator_salary', models.PositiveIntegerField()),
                ('coordinator_workday', models.PositiveIntegerField()),
                ('instructor_salary', models.PositiveIntegerField()),
                ('instructor_workday', models.PositiveIntegerField()),
                ('enumerator_salary', models.PositiveIntegerField()),
                ('enumerator_workday', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
