# Generated by Django 2.2.8 on 2020-02-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='census_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='census_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='coordinator_salary',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='coordinator_workday',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='enumerator_salary',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='enumerator_workday',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instructor_salary',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instructor_workday',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
