# Generated by Django 2.2.8 on 2020-02-24 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200224_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='census_end_date',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='census_start_date',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='coordinator_salary',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='coordinator_workday',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='enumerator_salary',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='enumerator_workday',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='instructor_salary',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='instructor_workday',
        ),
        migrations.CreateModel(
            name='RoleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('enum', 'Enumerator'), ('ins', 'Instructor'), ('cor', 'Coordinator')], max_length=50, null=True)),
                ('salary', models.PositiveIntegerField(null=True)),
                ('workday_start_date', models.DateField(null=True)),
                ('workday_end_date', models.DateField(null=True)),
                ('days_off', models.CharField(max_length=255)),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SiteSettings')),
            ],
        ),
    ]
