# Generated by Django 2.2.8 on 2020-02-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200224_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleinfo',
            name='days_off',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
