# Generated by Django 2.2.8 on 2020-02-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200224_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleinfo',
            name='days_off',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
