# Generated by Django 2.2.8 on 2020-02-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200224_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='gov_admin',
            field=models.CharField(max_length=255, verbose_name='Мам админстрация башчы (ААТ)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='PIN',
            field=models.CharField(max_length=14, unique=True, verbose_name='PIN'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport_num',
            field=models.CharField(max_length=7, unique=True, verbose_name='number of passport'),
        ),
    ]
