# Generated by Django 2.2.8 on 2020-02-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200224_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='stat_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
