# Generated by Django 2.2.8 on 2020-02-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_district_stat_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('cor', 'Coordinator')], default='cor', max_length=50, verbose_name='role'),
        ),
    ]
