# Generated by Django 2.2.8 on 2020-02-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200225_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(choices=[('chu', 'Чүй'), ('osh', 'Ош'), ('bat', 'Баткен'), ('jal', 'Жалал-Абад'), ('tal', 'Талас'), ('nar', 'Нарын'), ('kol', 'Ысык-Көл'), ('bis', 'г.Бишкек'), ('oshc', 'г.Ош')], max_length=9, unique=True, verbose_name='name'),
        ),
    ]
