# Generated by Django 2.2.8 on 2020-02-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200225_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dismissed',
            field=models.BooleanField(default=False, verbose_name='Dismissed?'),
        ),
    ]
