# Generated by Django 2.2.8 on 2020-02-25 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20200225_1702'),
        ('users', '0023_employee_dismissed'),
    ]

    operations = [
    ]
