# Generated by Django 2.2.8 on 2020-02-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_merge_20200225_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.CharField(choices=[('1', 'secondary vocational education'), ('2', 'bachelor'), ('3', 'master')], max_length=1, null=True, verbose_name='education'),
        ),
    ]
