# Generated by Django 2.2.8 on 2020-02-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_employee_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.CharField(choices=[('1', 'secondary vocational education'), ('2', 'bachelor'), ('3', 'master')], default=1, max_length=1, verbose_name='education'),
        ),
    ]
