# Generated by Django 2.2.8 on 2020-02-26 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20200225_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Territory', verbose_name='territory'),
        ),
    ]
