# Generated by Django 2.2.8 on 2020-02-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_district_did'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='counter',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
