# Generated by Django 2.2.8 on 2020-02-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20200226_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='counter',
            field=models.CharField(default='000001', max_length=6),
        ),
    ]
