# Generated by Django 2.2.8 on 2020-02-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20200226_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='workday',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roleinfo',
            name='workday_num',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
