# Generated by Django 2.2.8 on 2020-02-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20200226_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='workday',
            field=models.CharField(choices=[('full', 'full time work'), ('half', 'half time work')], default='full', max_length=4, verbose_name='workday'),
        ),
    ]
