# Generated by Django 2.2.8 on 2020-02-27 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20200226_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Territory', verbose_name='territory'),
        ),
    ]
