# Generated by Django 2.2.8 on 2020-02-27 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20200227_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.District', verbose_name='district'),
        ),
    ]
