# Generated by Django 2.2.8 on 2020-03-02 03:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20200227_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='role',
            field=models.CharField(choices=[('enum', 'Enumerator'), ('ins', 'Instructor'), ('cor', 'Coordinator')], max_length=50, null=True, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='number',
            field=models.CharField(error_messages={'unique': 'Мундай номер бар.'}, max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='must be in 555 500 000 format!', regex='^\\d{9}$')], verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('cor', 'Coordinator'), ('enum', 'Enumerator'), ('ins', 'Instructor')], default='cor', max_length=50, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='must be in 555 500 000 format!', regex='^\\d{9}$')], verbose_name='number'),
        ),
    ]
