# Generated by Django 2.2.8 on 2020-03-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20200302_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='role',
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('cor', 'Coordinator')], default='cor', max_length=50, verbose_name='role'),
        ),
    ]
