# Generated by Django 2.2.8 on 2020-03-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20200302_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='role',
            field=models.CharField(choices=[('enum', 'Enumerator'), ('ins', 'Instructor'), ('cor', 'Coordinator')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('cor', 'Coordinator'), ('enum', 'Enumerator'), ('ins', 'Instructor')], default='cor', max_length=50, verbose_name='role'),
        ),
    ]
