# Generated by Django 2.2.8 on 2020-03-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_region_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('cor', 'Coordinator'), ('enum', 'Enumerator'), ('enum1', 'Enumerator1'), ('ins', 'Instructor')], default='cor', max_length=50, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='role',
            field=models.CharField(choices=[('enum', 'Enumerator'), ('enum1', 'Enumerator1'), ('ins', 'Instructor'), ('cor', 'Coordinator')], max_length=50, null=True),
        ),
    ]
