# Generated by Django 2.2.8 on 2020-03-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20200306_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleinfo',
            name='role',
            field=models.CharField(choices=[('enum', 'Enumerator'), ('enum1', 'Enumerator1'), ('ins', 'Instructor'), ('cor', 'Coordinator')], max_length=50, null=True),
        ),
    ]
