# Generated by Django 2.2.8 on 2020-03-11 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20200308_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='login',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
    ]
