# Generated by Django 2.2.8 on 2020-03-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20200311_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='passport_num',
            field=models.CharField(max_length=7, verbose_name='number of passport'),
        ),
    ]
